[Settings]
; L key toggles hud on and off ingame on the fly
ToggleKey=76

; > for peek hud
PeekKey=190

; recap tab button (16 = shift)
ContinueKey=16
ContinueText=PRESS TO CONTINUE

; crt scan filter and film grain 
FX=1

; pauses cutscenes (80 = P) 
EnableCutscenePause=1
CSKey=80

; displays the old game clock under the armor and health bars (disabled by default)
GrandfatherClock=0